/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardUsersRouteImport } from './routes/dashboard/users'
import { Route as DashboardImportRouteImport } from './routes/dashboard/import'
import { Route as PublicPrivacyRouteImport } from './routes/_public/privacy'
import { Route as PublicImpressumRouteImport } from './routes/_public/impressum'
import { Route as PublicContributeRouteImport } from './routes/_public/contribute'
import { Route as DashboardInstancesRouteRouteImport } from './routes/dashboard/instances/route'
import { Route as DashboardInstancesIndexRouteImport } from './routes/dashboard/instances/index'
import { Route as PublicViewDataIndexRouteImport } from './routes/_public/view-data/index'
import { Route as DashboardInstancesInstanceIdRouteImport } from './routes/dashboard/instances/$instanceId'
import { Route as PublicViewDataInstanceIdRouteImport } from './routes/_public/view-data/$instanceId'
import { ServerRoute as OrpcServerRouteImport } from './routes/orpc'
import { ServerRoute as ApiSeedServerRouteImport } from './routes/api/seed'
import { ServerRoute as ApiRunJobsServerRouteImport } from './routes/api/run-jobs'
import { ServerRoute as ApiHealthcheckServerRouteImport } from './routes/api/healthcheck'
import { ServerRoute as ApiInstanceInstanceIdSessionsServerRouteImport } from './routes/api/instance/$instanceId/sessions'

const rootServerRouteImport = createServerRootRoute()

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardUsersRoute = DashboardUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardImportRoute = DashboardImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const PublicPrivacyRoute = PublicPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicImpressumRoute = PublicImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicContributeRoute = PublicContributeRouteImport.update({
  id: '/contribute',
  path: '/contribute',
  getParentRoute: () => PublicRouteRoute,
} as any)
const DashboardInstancesRouteRoute = DashboardInstancesRouteRouteImport.update({
  id: '/instances',
  path: '/instances',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardInstancesIndexRoute = DashboardInstancesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardInstancesRouteRoute,
} as any)
const PublicViewDataIndexRoute = PublicViewDataIndexRouteImport.update({
  id: '/view-data/',
  path: '/view-data/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const DashboardInstancesInstanceIdRoute =
  DashboardInstancesInstanceIdRouteImport.update({
    id: '/$instanceId',
    path: '/$instanceId',
    getParentRoute: () => DashboardInstancesRouteRoute,
  } as any)
const PublicViewDataInstanceIdRoute =
  PublicViewDataInstanceIdRouteImport.update({
    id: '/view-data/$instanceId',
    path: '/view-data/$instanceId',
    getParentRoute: () => PublicRouteRoute,
  } as any)
const OrpcServerRoute = OrpcServerRouteImport.update({
  id: '/orpc',
  path: '/orpc',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiSeedServerRoute = ApiSeedServerRouteImport.update({
  id: '/api/seed',
  path: '/api/seed',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiRunJobsServerRoute = ApiRunJobsServerRouteImport.update({
  id: '/api/run-jobs',
  path: '/api/run-jobs',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiHealthcheckServerRoute = ApiHealthcheckServerRouteImport.update({
  id: '/api/healthcheck',
  path: '/api/healthcheck',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiInstanceInstanceIdSessionsServerRoute =
  ApiInstanceInstanceIdSessionsServerRouteImport.update({
    id: '/api/instance/$instanceId/sessions',
    path: '/api/instance/$instanceId/sessions',
    getParentRoute: () => rootServerRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/instances': typeof DashboardInstancesRouteRouteWithChildren
  '/contribute': typeof PublicContributeRoute
  '/impressum': typeof PublicImpressumRoute
  '/privacy': typeof PublicPrivacyRoute
  '/dashboard/import': typeof DashboardImportRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/view-data/$instanceId': typeof PublicViewDataInstanceIdRoute
  '/dashboard/instances/$instanceId': typeof DashboardInstancesInstanceIdRoute
  '/view-data': typeof PublicViewDataIndexRoute
  '/dashboard/instances/': typeof DashboardInstancesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/contribute': typeof PublicContributeRoute
  '/impressum': typeof PublicImpressumRoute
  '/privacy': typeof PublicPrivacyRoute
  '/dashboard/import': typeof DashboardImportRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard': typeof DashboardIndexRoute
  '/view-data/$instanceId': typeof PublicViewDataInstanceIdRoute
  '/dashboard/instances/$instanceId': typeof DashboardInstancesInstanceIdRoute
  '/view-data': typeof PublicViewDataIndexRoute
  '/dashboard/instances': typeof DashboardInstancesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_public': typeof PublicRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/instances': typeof DashboardInstancesRouteRouteWithChildren
  '/_public/contribute': typeof PublicContributeRoute
  '/_public/impressum': typeof PublicImpressumRoute
  '/_public/privacy': typeof PublicPrivacyRoute
  '/dashboard/import': typeof DashboardImportRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/_public/view-data/$instanceId': typeof PublicViewDataInstanceIdRoute
  '/dashboard/instances/$instanceId': typeof DashboardInstancesInstanceIdRoute
  '/_public/view-data/': typeof PublicViewDataIndexRoute
  '/dashboard/instances/': typeof DashboardInstancesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/instances'
    | '/contribute'
    | '/impressum'
    | '/privacy'
    | '/dashboard/import'
    | '/dashboard/users'
    | '/dashboard/'
    | '/view-data/$instanceId'
    | '/dashboard/instances/$instanceId'
    | '/view-data'
    | '/dashboard/instances/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/contribute'
    | '/impressum'
    | '/privacy'
    | '/dashboard/import'
    | '/dashboard/users'
    | '/dashboard'
    | '/view-data/$instanceId'
    | '/dashboard/instances/$instanceId'
    | '/view-data'
    | '/dashboard/instances'
  id:
    | '__root__'
    | '/'
    | '/_public'
    | '/dashboard'
    | '/login'
    | '/dashboard/instances'
    | '/_public/contribute'
    | '/_public/impressum'
    | '/_public/privacy'
    | '/dashboard/import'
    | '/dashboard/users'
    | '/dashboard/'
    | '/_public/view-data/$instanceId'
    | '/dashboard/instances/$instanceId'
    | '/_public/view-data/'
    | '/dashboard/instances/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}
export interface FileServerRoutesByFullPath {
  '/orpc': typeof OrpcServerRoute
  '/api/healthcheck': typeof ApiHealthcheckServerRoute
  '/api/run-jobs': typeof ApiRunJobsServerRoute
  '/api/seed': typeof ApiSeedServerRoute
  '/api/instance/$instanceId/sessions': typeof ApiInstanceInstanceIdSessionsServerRoute
}
export interface FileServerRoutesByTo {
  '/orpc': typeof OrpcServerRoute
  '/api/healthcheck': typeof ApiHealthcheckServerRoute
  '/api/run-jobs': typeof ApiRunJobsServerRoute
  '/api/seed': typeof ApiSeedServerRoute
  '/api/instance/$instanceId/sessions': typeof ApiInstanceInstanceIdSessionsServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/orpc': typeof OrpcServerRoute
  '/api/healthcheck': typeof ApiHealthcheckServerRoute
  '/api/run-jobs': typeof ApiRunJobsServerRoute
  '/api/seed': typeof ApiSeedServerRoute
  '/api/instance/$instanceId/sessions': typeof ApiInstanceInstanceIdSessionsServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths:
    | '/orpc'
    | '/api/healthcheck'
    | '/api/run-jobs'
    | '/api/seed'
    | '/api/instance/$instanceId/sessions'
  fileServerRoutesByTo: FileServerRoutesByTo
  to:
    | '/orpc'
    | '/api/healthcheck'
    | '/api/run-jobs'
    | '/api/seed'
    | '/api/instance/$instanceId/sessions'
  id:
    | '__root__'
    | '/orpc'
    | '/api/healthcheck'
    | '/api/run-jobs'
    | '/api/seed'
    | '/api/instance/$instanceId/sessions'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  OrpcServerRoute: typeof OrpcServerRoute
  ApiHealthcheckServerRoute: typeof ApiHealthcheckServerRoute
  ApiRunJobsServerRoute: typeof ApiRunJobsServerRoute
  ApiSeedServerRoute: typeof ApiSeedServerRoute
  ApiInstanceInstanceIdSessionsServerRoute: typeof ApiInstanceInstanceIdSessionsServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/users': {
      id: '/dashboard/users'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardUsersRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/import': {
      id: '/dashboard/import'
      path: '/import'
      fullPath: '/dashboard/import'
      preLoaderRoute: typeof DashboardImportRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_public/privacy': {
      id: '/_public/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PublicPrivacyRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/impressum': {
      id: '/_public/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof PublicImpressumRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/contribute': {
      id: '/_public/contribute'
      path: '/contribute'
      fullPath: '/contribute'
      preLoaderRoute: typeof PublicContributeRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/dashboard/instances': {
      id: '/dashboard/instances'
      path: '/instances'
      fullPath: '/dashboard/instances'
      preLoaderRoute: typeof DashboardInstancesRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/instances/': {
      id: '/dashboard/instances/'
      path: '/'
      fullPath: '/dashboard/instances/'
      preLoaderRoute: typeof DashboardInstancesIndexRouteImport
      parentRoute: typeof DashboardInstancesRouteRoute
    }
    '/_public/view-data/': {
      id: '/_public/view-data/'
      path: '/view-data'
      fullPath: '/view-data'
      preLoaderRoute: typeof PublicViewDataIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/dashboard/instances/$instanceId': {
      id: '/dashboard/instances/$instanceId'
      path: '/$instanceId'
      fullPath: '/dashboard/instances/$instanceId'
      preLoaderRoute: typeof DashboardInstancesInstanceIdRouteImport
      parentRoute: typeof DashboardInstancesRouteRoute
    }
    '/_public/view-data/$instanceId': {
      id: '/_public/view-data/$instanceId'
      path: '/view-data/$instanceId'
      fullPath: '/view-data/$instanceId'
      preLoaderRoute: typeof PublicViewDataInstanceIdRouteImport
      parentRoute: typeof PublicRouteRoute
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/orpc': {
      id: '/orpc'
      path: '/orpc'
      fullPath: '/orpc'
      preLoaderRoute: typeof OrpcServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/seed': {
      id: '/api/seed'
      path: '/api/seed'
      fullPath: '/api/seed'
      preLoaderRoute: typeof ApiSeedServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/run-jobs': {
      id: '/api/run-jobs'
      path: '/api/run-jobs'
      fullPath: '/api/run-jobs'
      preLoaderRoute: typeof ApiRunJobsServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/healthcheck': {
      id: '/api/healthcheck'
      path: '/api/healthcheck'
      fullPath: '/api/healthcheck'
      preLoaderRoute: typeof ApiHealthcheckServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/instance/$instanceId/sessions': {
      id: '/api/instance/$instanceId/sessions'
      path: '/api/instance/$instanceId/sessions'
      fullPath: '/api/instance/$instanceId/sessions'
      preLoaderRoute: typeof ApiInstanceInstanceIdSessionsServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

interface PublicRouteRouteChildren {
  PublicContributeRoute: typeof PublicContributeRoute
  PublicImpressumRoute: typeof PublicImpressumRoute
  PublicPrivacyRoute: typeof PublicPrivacyRoute
  PublicViewDataInstanceIdRoute: typeof PublicViewDataInstanceIdRoute
  PublicViewDataIndexRoute: typeof PublicViewDataIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicContributeRoute: PublicContributeRoute,
  PublicImpressumRoute: PublicImpressumRoute,
  PublicPrivacyRoute: PublicPrivacyRoute,
  PublicViewDataInstanceIdRoute: PublicViewDataInstanceIdRoute,
  PublicViewDataIndexRoute: PublicViewDataIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

interface DashboardInstancesRouteRouteChildren {
  DashboardInstancesInstanceIdRoute: typeof DashboardInstancesInstanceIdRoute
  DashboardInstancesIndexRoute: typeof DashboardInstancesIndexRoute
}

const DashboardInstancesRouteRouteChildren: DashboardInstancesRouteRouteChildren =
  {
    DashboardInstancesInstanceIdRoute: DashboardInstancesInstanceIdRoute,
    DashboardInstancesIndexRoute: DashboardInstancesIndexRoute,
  }

const DashboardInstancesRouteRouteWithChildren =
  DashboardInstancesRouteRoute._addFileChildren(
    DashboardInstancesRouteRouteChildren,
  )

interface DashboardRouteRouteChildren {
  DashboardInstancesRouteRoute: typeof DashboardInstancesRouteRouteWithChildren
  DashboardImportRoute: typeof DashboardImportRoute
  DashboardUsersRoute: typeof DashboardUsersRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardInstancesRouteRoute: DashboardInstancesRouteRouteWithChildren,
  DashboardImportRoute: DashboardImportRoute,
  DashboardUsersRoute: DashboardUsersRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PublicRouteRoute: PublicRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  OrpcServerRoute: OrpcServerRoute,
  ApiHealthcheckServerRoute: ApiHealthcheckServerRoute,
  ApiRunJobsServerRoute: ApiRunJobsServerRoute,
  ApiSeedServerRoute: ApiSeedServerRoute,
  ApiInstanceInstanceIdSessionsServerRoute:
    ApiInstanceInstanceIdSessionsServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
